# ==== Default vis macro for mu-raquette ====

# Set verbose
/control/verbose 0
/run/verbose 0
/vis/verbose errors
/tracking/verbose 1

# Create and empty scene
/vis/open OGL 600x600-0+0

# Draw scene
/vis/drawVolume
/vis/viewer/set/projection p
/vis/viewer/set/viewpointThetaPhi 45 90 deg
/vis/viewer/zoom 1


# Draw the tracks
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate
/vis/viewer/set/autoRefresh true
